--Bank Data Modules------
DELETE FROM CALENDAR WHERE CALENDARCODE IN ('HSBC','DBS');
DELETE FROM REGION WHERE REGIONCODE IN ('HSBC','DBS');
DELETE FROM COUNTRY WHERE COUNTRYCODE IN ('IN','CA');
DELETE FROM CURRENCY WHERE CURRENCYNAME IN ('HSBC Currency Code','DBS Currency Code');
DELETE FROM DEPARTMENT WHERE DEPARTMENTCODE IN ('HDBCDEPT','DBSDEPT');
DELETE FROM OFFICE WHERE OFFICECODE IN ('HSBCOFF','DBSOFF');
DELETE FROM BRANCH WHERE BRANCHCODE IN ('HSBCBranch','DBSBranch');
DELETE FROM FXRATECHART WHERE OFFICECODE IN ('HSBCOFF','DBSOFF');

-- OnBoarding Data------
DELETE FROM SERVICE WHERE SERVICENAME IN ('HSBC Service Code','DBS Service Code');
DELETE FROM SERVICEGROUP WHERE SERVICEGROUPCODE IN ('HSBC','DBS');
DELETE FROM PARTY WHERE PARTYCODE IN ('HSBC007','DBS007');
DELETE FROM PRODUCT WHERE PRODUCTCODE IN  ('HSBC','DBS');
DELETE FROM ACCOUNT WHERE ACCOUNTNO IN ('14564','425445');

--------Distribution Data--------------
DELETE FROM BANKROUTING WHERE BRANCH='ESBRANCH';
DELETE FROM COUNTRYCORRESPONDENT WHERE COUNTRYCODE ='AF';
DELETE FROM CURRENCYCORRESPONDENT WHERE CURRENCYCODE ='AUD';
DELETE FROM MOPPRIORITY WHERE MOP = 'TESTMOP';
DELETE FROM MOP WHERE MOP ='TESTMOP';
DELETE FROM BULKPROFILEOVERRIDE WHERE BULKPROFILE ='TestProfile';
DELETE FROM BULKPROFILE WHERE BULKPROFILECODE ='TestProfile';
DELETE FROM CUTOFF WHERE CUTOFFCODE='TestCOT';

--------------System Data----------------
DELETE FROM VOLPAYCONFIGURATION WHERE NAME ='test';
DELETE FROM VOLPAYIDCONFIGURATION WHERE PATTERN ='code';
DELETE FROM ACTIONDEFINITION WHERE ACTIONNAME ='test';
DELETE FROM STATUSDEFINITION WHERE PROCESSSTATUS ='test';
DELETE FROM INCIDENCEDEFINITION WHERE INCIDENCECODE='PMNTDUP101' AND PROCESSSTATUS='STP';
DELETE FROM RESOURCEAPPROVALPERMISSION WHERE APPROVALCOUNT='4';


